default = "/Users/NanoomLee/Documents/Master@StonyBrook/ISW_21cm_Code/ISW_21cm"
path_CLASS_syn = default + "/class_syn"
path_CLASS_new = default + "/class_new"
path_HYREC = default + "/HyRec"
path_result_Yp_BBN = default + "/result_Yp_BBN"
path_result_Yp = default + "/result_Yp"
path_data = default + "/data"
path_params_Yp_BBN = default + "/params_Yp_BBN"
path_params_Yp = default + "/params_Yp"
result_Yp_BBN = default + "/result_Yp_BBN"
result_Yp = default + "/result_Yp"

